const cards = {
  emotions: [
    {
      name: 'angry',
      nameLT: 'piktas',
      media: 'angry',
      state: 'closed',
    },
    {
      name: 'sad',
      nameLT: 'liūdnas',
      media: 'sad',
      state: 'closed',
    },
    {
      name: 'scared',
      nameLT: 'išsigandęs',
      media: 'scared',
      state: 'closed',
    },
    {
      name: 'surprised',
      nameLT: 'nustebęs',
      media: 'surprised',
      state: 'closed',
    },
    {
      name: 'tired',
      nameLT: 'pavargęs',
      media: 'tired',
      state: 'closed',
    },
    {
      name: 'happy',
      nameLT: 'laimingas',
      media: 'happy',
      state: 'closed',
    },
    {
      name: 'laugh',
      nameLT: 'juoktis',
      media: 'laugh',
      state: 'closed',
    },
    {
      name: 'smile',
      nameLT: 'šypsotis',
      media: 'smile',
      state: 'closed',
    },
  ],
  clothes: [
    {
      name: 'blouse',
      nameLT: 'marškinėliai',
      media: 'blouse',
      state: 'closed',
    },
    {
      name: 'boot',
      nameLT: 'batas',
      media: 'boot',
      state: 'closed',
    },
    {
      name: 'coat',
      nameLT: 'paltas',
      media: 'coat',
      state: 'closed',
    },
    {
      name: 'dress',
      nameLT: 'suknelė',
      media: 'dress',
      state: 'closed',
    },
    {
      name: 'pants',
      nameLT: 'kelnės',
      media: 'pants',
      state: 'closed',
    },
    {
      name: 'shirt',
      nameLT: 'marškiniai',
      media: 'shirt',
      state: 'closed',
    },
    {
      name: 'skirt',
      nameLT: 'sijonas',
      media: 'skirt',
      state: 'closed',
    },
    {
      name: 'shoe',
      nameLT: 'batelis',
      media: 'shoe',
      state: 'closed',
    },
  ],
  animals: [
    {
      name: 'bird',
      nameLT: 'paukštis',
      media: 'bird',
      state: 'closed',
    },
    {
      name: 'cat',
      nameLT: 'katė',
      media: 'cat',
      state: 'closed',
    },
    {
      name: 'chick',
      nameLT: 'viščiukas',
      media: 'chick',
      state: 'closed',
    },
    {
      name: 'chicken',
      nameLT: 'višta',
      media: 'chicken',
      state: 'closed',
    },
    {
      name: 'dog',
      nameLT: 'šuo',
      media: 'dog',
      state: 'closed',
    },
    {
      name: 'dolphin',
      nameLT: 'delfinas',
      media: 'dolphin',
      state: 'closed',
    },
    {
      name: 'fish',
      nameLT: 'žuvis',
      media: 'fish',
      state: 'closed',
    },
    {
      name: 'frog',
      nameLT: 'varlė',
      media: 'frog',
      state: 'closed',
    },
  ],
  animals2: [
    {
      name: 'giraffe',
      nameLT: 'žirafa',
      media: 'giraffe',
      state: 'closed',
    },
    {
      name: 'horse',
      nameLT: 'arklys',
      media: 'horse',
      state: 'closed',
    },
    {
      name: 'lion',
      nameLT: 'liūtas',
      media: 'lion',
      state: 'closed',
    },
    {
      name: 'mouse',
      nameLT: 'pelė',
      media: 'mouse',
      state: 'closed',
    },
    {
      name: 'pig',
      nameLT: 'kiaulė',
      media: 'pig',
      state: 'closed',
    },
    {
      name: 'rabbit',
      nameLT: 'triušis',
      media: 'rabbit',
      state: 'closed',
    },
    {
      name: 'sheep',
      nameLT: 'avis',
      media: 'sheep',
      state: 'closed',
    },
    {
      name: 'turtle',
      nameLT: 'vėžlys',
      media: 'turtle',
      state: 'closed',
    },
  ],
  action1: [
    {
      name: 'cry',
      nameLT: 'verkti',
      media: 'cry',
      state: 'closed',
    },
    {
      name: 'dance',
      nameLT: 'šokti',
      media: 'dance',
      state: 'closed',
    },
    {
      name: 'dive',
      nameLT: 'nerti',
      media: 'dive',
      state: 'closed',
    },
    {
      name: 'draw',
      nameLT: 'piešti',
      media: 'draw',
      state: 'closed',
    },
    {
      name: 'fly',
      nameLT: 'skristi',
      media: 'fly',
      state: 'closed',
    },
    {
      name: 'hug',
      nameLT: 'apkabinti',
      media: 'hug',
      state: 'closed',
    },
    {
      name: 'jump',
      nameLT: 'šokti',
      media: 'jump',
      state: 'closed',
    },
    {
      name: 'open',
      nameLT: 'atidaryti',
      media: 'open',
      state: 'closed',
    },
  ],
  action2: [
    {
      name: 'play',
      nameLT: 'žaisti',
      media: 'play',
      state: 'closed',
    },
    {
      name: 'point',
      nameLT: 'rodyti',
      media: 'point',
      state: 'closed',
    },
    {
      name: 'ride',
      nameLT: 'jodinėti',
      media: 'ride',
      state: 'closed',
    },
    {
      name: 'run',
      nameLT: 'bėgti',
      media: 'run',
      state: 'closed',
    },
    {
      name: 'skip',
      nameLT: 'šokinėti šokdyne',
      media: 'skip',
      state: 'closed',
    },
    {
      name: 'swim',
      nameLT: 'plaukti',
      media: 'swim',
      state: 'closed',
    },
    {
      name: 'sing',
      nameLT: 'dainuoti',
      media: 'sing',
      state: 'closed',
    },
    {
      name: 'laugh',
      nameLT: 'juoktis',
      media: 'laugh',
      state: 'closed',
    },
  ],
};

module.exports = { cards };
